/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "int.h"

void delay(void)
{
	for(uint32_t i = 0 ; i< 300000 ; i++);
}

uint32_t* EXTI_PR = (uint32_t*) ( EXTI_BASEADDR + 0x14U ) ;

uint32_t* GPIOB_IDR = (uint32_t*) ( GPIOB_IDRADDR ) ;

uint32_t* GPIOA_ODR1 = (uint32_t*)GPIOA_ODRADDR;

/*
 * POINTERS FOR LEDs
 */
extern uint32_t* GPIOA_MODER; // Use the one from int.c
extern uint32_t* GPIOB_MODER; // Use the one from int.c
uint32_t* GPIOB_ODR = (uint32_t*) ( GPIOB_BASEADDR + 0x14U ); // This one is new, so we define it


/*
 * FUNCTION TO CONFIGURE LEDS
 */
void LED_GPIO_Init(void)
{
    // Note: GPIOA and GPIOB clocks are already enabled by GPIO() in int.c
    // We just need to set the MODER registers for PA9 and PB10.

    // Set PA9 to General-purpose output mode (01)
    *GPIOA_MODER &= ~(3U << 18); // Clear bits 19:18
    *GPIOA_MODER |= (1U << 18);  // Set to 01

    // Set PB10 to General-purpose output mode (01)
    *GPIOB_MODER &= ~(3U << 20); // Clear bits 21:20
    *GPIOB_MODER |= (1U << 20);  // Set to 01
}


int main(void)
{
	GPIO();
	INT();
	LED_GPIO_Init();

	for(;;);
}


void EXTI9_5_IRQHandler(void)
{
    if (*EXTI_PR & (1 << 6))
    {
    	delay(); // This is the debounce delay
    	*EXTI_PR |= (1 << 6);
    	*GPIOA_ODR1 &= ~(1 << 5); // PA5 LOW

    	if(!(*GPIOB_IDR  & ( 1 << 6 )))
    	{
    		//Key is Pressed
    		printf("1\n");
    		*GPIOA_ODR1 ^= (1 << 9); // Toggle PA9
    	}

    	*GPIOA_ODR1 |= (1 << 5); // PA5 HIGH

    	*GPIOA_ODR1 &= ~(1 << 6); // PA6 LOW
    	if(!(*GPIOB_IDR  & ( 1 << 6 )))
    	{
    		//Key is Pressed
    		printf("4\n");
    		*GPIOB_ODR ^= (1 << 10); // Toggle PB10
    	}
    	*GPIOA_ODR1 |= (1 << 6); // PA6 HIGH

    	*GPIOA_ODR1 &= ~(1 << 7); // PA7 LOW
    	if(!(*GPIOB_IDR  & ( 1 << 6 )))
    	{
    		//Key is Pressed
    		printf("7\n");
    		*GPIOA_ODR1 ^= (1 << 9); // Toggle PA9
    		*GPIOB_ODR ^= (1 << 10); // Toggle PB10
    	}

    	*GPIOA_ODR1 |= (1 << 7); // PA7 HIGH

    	*GPIOA_ODR1 &= ~(1 << 8); // PA8 LOW
    	if(!(*GPIOB_IDR  & ( 1 << 6 )))
    	{
    		//Key is Pressed
    		printf("*\n");
    		*GPIOA_ODR1 |= (1 << 9); // PA9 ON
    		*GPIOB_ODR |= (1 << 10); // PB10 ON
    	}

    	*GPIOA_ODR1 |= (1 << 8); // PA8 HIGH
    }

    if (*EXTI_PR & (1 << 7))
    {
    	delay();  // This is the debounce delay
    	*EXTI_PR |= (1 << 7);

    	*GPIOA_ODR1 &= ~(1 << 5); // PA5 LOW

    	if(!(*GPIOB_IDR  & ( 1 << 7 )))
    	{
    		//Key is Pressed
    		printf("2\n");
    		*GPIOA_ODR1 ^= (1 << 9); // Toggle PA9
    	}

    	*GPIOA_ODR1 |= (1 << 5); // PA5 HIGH

    	*GPIOA_ODR1 &= ~(1 << 6); // PA6 LOW
    	if(!(*GPIOB_IDR  & ( 1 << 7 )))
    	{
    		//Key is Pressed
    		printf("5\n");
    		*GPIOB_ODR ^= (1 << 10); // Toggle PB10
    	}
    	*GPIOA_ODR1 |= (1 << 6); // PA6 HIGH

    	*GPIOA_ODR1 &= ~(1 << 7); // PA7 LOW
    	if(!(*GPIOB_IDR  & ( 1 << 7 )))
    	{
    		//Key is Pressed
    		printf("8\n");
    		*GPIOA_ODR1 ^= (1 << 9); // Toggle PA9
    		*GPIOB_ODR ^= (1 << 10); // Toggle PB10
    	}

    	*GPIOA_ODR1 |= (1 << 7); // PA7 HIGH

    	*GPIOA_ODR1 &= ~(1 << 8); // PA8 LOW
    	if(!(*GPIOB_IDR  & ( 1 << 7 )))
    	{
    		//Key is Pressed
    		printf("0\n");
    		*GPIOA_ODR1 &= ~(1 << 9); // PA9 OFF
    		*GPIOB_ODR &= ~(1 << 10); // PB10 OFF
    	}

    	*GPIOA_ODR1 |= (1 << 8); // PA8 HIGH
    }

    if (*EXTI_PR & (1 << 8))
    {
    	delay(); // This is the debounce delay

    	*EXTI_PR |= (1 << 8);

    	*GPIOA_ODR1 &= ~(1 << 5); // PA5 LOW

    	if(!(*GPIOB_IDR  & ( 1 << 8 )))
    	{
    		//Key is Pressed
    		printf("3\n");
    		*GPIOA_ODR1 ^= (1 << 9); // Toggle PA9
    	}

    	*GPIOA_ODR1 |= (1 << 5); // PA5 HIGH

    	*GPIOA_ODR1 &= ~(1 << 6); // PA6 LOW
    	if(!(*GPIOB_IDR  & ( 1 << 8 )))
    	{
    		//Key is Pressed
    		printf("6\n");
    		*GPIOB_ODR ^= (1 << 10); // Toggle PB10
    	}
    	*GPIOA_ODR1 |= (1 << 6); // PA6 HIGH

    	*GPIOA_ODR1 &= ~(1 << 7); // PA7 LOW
    	if(!(*GPIOB_IDR  & ( 1 << 8 )))
    	{
    		//Key is Pressed
    		printf("9\n");
    		*GPIOA_ODR1 ^= (1 << 9); // Toggle PA9
    		*GPIOB_ODR ^= (1 << 10); // Toggle PB10
    	}

    	*GPIOA_ODR1 |= (1 << 7); // PA7 HIGH

    	*GPIOA_ODR1 &= ~(1 << 8); // PA8 LOW
    	if(!(*GPIOB_IDR  & ( 1 << 8 )))
    	{
    		//Key is Pressed
    		printf("#\n");
    		*GPIOA_ODR1 |= (1 << 9); // PA9 ON
    		*GPIOB_ODR |= (1 << 10); // PB10 ON
    	}

    	*GPIOA_ODR1 |= (1 << 8); // PA8 HIGH
    }

    if (*EXTI_PR & (1 << 9))
    {
    	delay(); // This is the debounce delay

        *EXTI_PR |= (1 << 9);
    	*GPIOA_ODR1 &= ~(1 << 5); // PA5 LOW

    	if(!(*GPIOB_IDR  & ( 1 << 9 )))
    	{
    		//Key is Pressed
    		printf("A\n");
    		// No LED action
    	}

    	*GPIOA_ODR1 |= (1 << 5); // PA5 HIGH

    	*GPIOA_ODR1 &= ~(1 << 6); // PA6 LOW
    	if(!(*GPIOB_IDR  & ( 1 << 9 )))
    	{
    		//Key is Pressed
    		printf("B\n");
    		// No LED action
    	}
    	*GPIOA_ODR1 |= (1 << 6); // PA6 HIGH

    	*GPIOA_ODR1 &= ~(1 << 7); // PA7 LOW
    	if(!(*GPIOB_IDR  & ( 1 << 9 )))
    	{
    		//Key is Pressed
    		printf("C\n");
    		// No LED action
    	}

    	*GPIOA_ODR1 |= (1 << 7); // PA7 HIGH

    	*GPIOA_ODR1 &= ~(1 << 8); // PA8 LOW
    	if(!(*GPIOB_IDR  & ( 1 << 9 )))
    	{
    		//Key is Pressed
    		printf("D\n");
    		// No LED action
    	}

    	*GPIOA_ODR1 |= (1 << 8); // PA8 HIGH
    }
}
