/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "int.h"

void delay(void)
{
	for(uint32_t i = 0 ; i< 250000 ; i++);
}

uint32_t* EXTI_PR = (uint32_t*) ( EXTI_BASEADDR + 0x14U ) ;

uint32_t* GPIOB_IDR = (uint32_t*) ( GPIOB_IDRADDR ) ;

uint32_t* GPIOA_ODR1 = (uint32_t*)GPIOA_ODRADDR;

int main(void)
{
	GPIO();
	INT();
	for(;;);
}


void EXTI9_5_IRQHandler(void)
{
    if (*EXTI_PR & (1 << 6))
    {
    	delay();
    	*EXTI_PR |= (1 << 6);
    	*GPIOA_ODR1 &= ~(1 << 5); // PA5 LOW

    	if(!(*GPIOB_IDR  & ( 1 << 6 )))
    	{
    		//Key is Pressed
    		delay();
    		printf("1\n");

    	}

    	*GPIOA_ODR1 |= (1 << 5); // PA5 HIGH

    	*GPIOA_ODR1 &= ~(1 << 6); // PA6 LOW
    	if(!(*GPIOB_IDR  & ( 1 << 6 )))
    	{
    		//Key is Pressed
    		delay();
    		printf("4\n");

    	}
    	*GPIOA_ODR1 |= (1 << 6); // PA6 HIGH

    	*GPIOA_ODR1 &= ~(1 << 7); // PA7 LOW
    	if(!(*GPIOB_IDR  & ( 1 << 6 )))
    	{
    		//Key is Pressed
    		delay();
    		printf("7\n");

    	}

    	*GPIOA_ODR1 |= (1 << 7); // PA7 HIGH

    	*GPIOA_ODR1 &= ~(1 << 8); // PA8 LOW
    	if(!(*GPIOB_IDR  & ( 1 << 6 )))
    	{
    		//Key is Pressed
    		delay();
    		printf("*\n");

    	}

    	*GPIOA_ODR1 |= (1 << 8); // PA8 HIGH
    }

    if (*EXTI_PR & (1 << 7))
    {
    	delay();
    	*EXTI_PR |= (1 << 7);

    	*GPIOA_ODR1 &= ~(1 << 5); // PA5 LOW

    	if(!(*GPIOB_IDR  & ( 1 << 7 )))
    	{
    		//Key is Pressed
    		delay();
    		printf("2\n");

    	}

    	*GPIOA_ODR1 |= (1 << 5); // PA5 HIGH

    	*GPIOA_ODR1 &= ~(1 << 6); // PA6 LOW
    	if(!(*GPIOB_IDR  & ( 1 << 7 )))
    	{
    		//Key is Pressed
    		delay();
    		printf("5\n");

    	}
    	*GPIOA_ODR1 |= (1 << 6); // PA6 HIGH

    	*GPIOA_ODR1 &= ~(1 << 7); // PA7 LOW
    	if(!(*GPIOB_IDR  & ( 1 << 7 )))
    	{
    		//Key is Pressed
    		delay();
    		printf("8\n");

    	}

    	*GPIOA_ODR1 |= (1 << 7); // PA7 HIGH

    	*GPIOA_ODR1 &= ~(1 << 8); // PA8 LOW
    	if(!(*GPIOB_IDR  & ( 1 << 7 )))
    	{
    		//Key is Pressed
    		delay();
    		printf("0\n");

    	}

    	*GPIOA_ODR1 |= (1 << 8); // PA8 HIGH
    }

    if (*EXTI_PR & (1 << 8))
    {
    	delay();

    	*EXTI_PR |= (1 << 8);

    	*GPIOA_ODR1 &= ~(1 << 5); // PA5 LOW

    	if(!(*GPIOB_IDR  & ( 1 << 8 )))
    	{
    		//Key is Pressed
    		delay();
    		printf("3\n");

    	}

    	*GPIOA_ODR1 |= (1 << 5); // PA5 HIGH

    	*GPIOA_ODR1 &= ~(1 << 6); // PA6 LOW
    	if(!(*GPIOB_IDR  & ( 1 << 8 )))
    	{
    		//Key is Pressed
    		delay();
    		printf("6\n");

    	}
    	*GPIOA_ODR1 |= (1 << 6); // PA6 HIGH

    	*GPIOA_ODR1 &= ~(1 << 7); // PA7 LOW
    	if(!(*GPIOB_IDR  & ( 1 << 8 )))
    	{
    		//Key is Pressed
    		delay();
    		printf("9\n");

    	}

    	*GPIOA_ODR1 |= (1 << 7); // PA7 HIGH

    	*GPIOA_ODR1 &= ~(1 << 8); // PA8 LOW
    	if(!(*GPIOB_IDR  & ( 1 << 8 )))
    	{
    		//Key is Pressed
    		delay();
    		printf("#\n");

    	}

    	*GPIOA_ODR1 |= (1 << 8); // PA8 HIGH
    }

    if (*EXTI_PR & (1 << 9))
    {
    	delay();

        *EXTI_PR |= (1 << 9);
    	*GPIOA_ODR1 &= ~(1 << 5); // PA5 LOW

    	if(!(*GPIOB_IDR  & ( 1 << 9 )))
    	{
    		//Key is Pressed
    		delay();
    		printf("A\n");

    	}

    	*GPIOA_ODR1 |= (1 << 5); // PA5 HIGH

    	*GPIOA_ODR1 &= ~(1 << 6); // PA6 LOW
    	if(!(*GPIOB_IDR  & ( 1 << 9 )))
    	{
    		//Key is Pressed
    		delay();
    		printf("B\n");

    	}
    	*GPIOA_ODR1 |= (1 << 6); // PA6 HIGH

    	*GPIOA_ODR1 &= ~(1 << 7); // PA7 LOW
    	if(!(*GPIOB_IDR  & ( 1 << 9 )))
    	{
    		//Key is Pressed
    		delay();
    		printf("C\n");

    	}

    	*GPIOA_ODR1 |= (1 << 7); // PA7 HIGH

    	*GPIOA_ODR1 &= ~(1 << 8); // PA8 LOW
    	if(!(*GPIOB_IDR  & ( 1 << 9 )))
    	{
    		//Key is Pressed
    		delay();
    		printf("D\n");

    	}

    	*GPIOA_ODR1 |= (1 << 8); // PA8 HIGH
    }
}
