/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "spi.h"

#define GPIOB_BASEADDR			0x40020400U
#define RCC_AHB1ENR_ADDR		RCC_BASEADDR +  0x30U
#define GPIOB_MODER_ADDR		GPIOB_BASEADDR + 0x00U
#define GPIOB_OSPEEDR_ADDR		GPIOB_BASEADDR + 0x08U
#define GPIOB_AFRH_ADDR			GPIOB_BASEADDR + 0x20U//(0101)

void GPIO_Init(void)
{
	/*
	 * Alternate Function Mode : 5
	 * PB12 --> NSS
	 * PB13 --> SCK
	 * PB14 --> MISO
	 * PB15 --> MOSI
	 */
	uint32_t *AHB1ENR = (uint32_t *) RCC_AHB1ENR_ADDR;
	uint32_t *GPIOB_MODER = (uint32_t *) GPIOB_MODER_ADDR;
	uint32_t *GPIOB_OSPEEDR = (uint32_t *) GPIOB_OSPEEDR_ADDR;
	uint32_t *GPIOB_AFRH = (uint32_t *) GPIOB_AFRH_ADDR;

	// 1. Enable GPIOB Peripheral Clock
	*AHB1ENR &= ~( 1U << 1);	//Reset Bit
	*AHB1ENR |= ( 1U << 1);		//Set Bit


	// 2. Set Mode as Alternate function
	//PB12
	*GPIOB_MODER &= ~( 3U << 24); //Reset Bit
	*GPIOB_MODER |= ( 2U << 24); //Set Bit

	//PB13
	*GPIOB_MODER &= ~( 3U << 26); //Reset Bit
	*GPIOB_MODER |= ( 2U << 26); //Set Bit

	//PB14
	*GPIOB_MODER &= ~( 3U << 28); //Reset Bit
	*GPIOB_MODER |= ( 2U << 28); //Set Bit

	//PB15
	*GPIOB_MODER &= ~( 3U << 30); //Reset Bit
	*GPIOB_MODER |= ( 2U << 30); //Set Bit


	//3. Set Speed
	//PB12
	*GPIOB_OSPEEDR &= ~( 3U << 24); //Reset Bit
	*GPIOB_OSPEEDR |= ( 3U << 25); //Set Bit

	//PB13
	*GPIOB_OSPEEDR &= ~( 3U << 26); //Reset Bit
	*GPIOB_OSPEEDR |= ( 3U << 27); //Set Bit

	//PB14
	*GPIOB_OSPEEDR &= ~( 3U << 28); //Reset Bit
	*GPIOB_OSPEEDR |= ( 3U << 29); //Set Bit

	//PB15
	*GPIOB_OSPEEDR &= ~( 3U << 30); //Reset Bit
	*GPIOB_OSPEEDR |= ( 3U << 31); //Set Bit

	//4. Select AF Mode 5
	//PB12
	*GPIOB_AFRH &= ~( 15U << 16); //Reset Bit
	*GPIOB_AFRH |= ( 5U << 16); //Set Bit

	//PB13
	*GPIOB_AFRH &= ~( 15U << 20); //Reset Bit
	*GPIOB_AFRH |= ( 5U << 20); //Set Bit

	//PB14
	*GPIOB_AFRH &= ~( 15U << 24); //Reset Bit
	*GPIOB_AFRH |= ( 5U << 24); //Set Bit

	//PB15
	*GPIOB_AFRH &= ~( 15U << 28); //Reset Bit
	*GPIOB_AFRH |= ( 5U << 28); //Set Bit
}
int main(void)
{
	GPIO_Init();
	for(;;);
}
